export const content = {
  en: {
    title: 'CyberAlps | Website & web application development',
    description: 'We design and develop websites and web applications for your business. From a new website to integrations, SEO, AI search visibility and ongoing improvements.',
    nav: ['Services', 'How we work', 'Website check', 'Contact'], check: 'Check my website',
    eyebrow: 'WEBSITE & WEB APPLICATION DEVELOPMENT', hero1: 'Your next website.', hero2: 'Built around you.',
    intro: 'We design and develop websites and web applications for your business.', intro2: 'From the first idea to launch — and the improvements that come next.',
    project: 'Discuss your project', explore: 'Explore our services', existing: 'Already have a website? Check it for free',
    studioTitle: 'From idea to a working website.', studioLabel: 'WHAT WE BUILD', studioItems: ['Business websites', 'Web applications', 'Integrations & automation'],
    studioFoot: 'Design · Development · Launch · Support',
    auditEyebrow: 'FOR YOUR EXISTING WEBSITE', auditTitle: 'A useful starting point.', auditIntro: 'Check the technical basics of your website. Then decide what to improve — with our help if you need it.',
    placeholder: 'Enter your website URL', run: 'Run free check', consent: 'I own this website or have permission to check it.',
    scope: 'SEO & GEO · Security · Technical readiness', exampleLink: 'See an example report',
    example: 'Example report', demo: 'DEMO', live: 'Your website check', next: 'Recommended next steps',
    turn: 'Turn findings into fixes', plan: 'View action plan', reportTitle: 'Your next steps, in plain language.',
    reportIntro: 'A preliminary check of one page and its discovery files. Open a finding to see the evidence and a suggested next step.',
    checked: 'Checked', issues: 'To review', unknown: 'Not checked', good: 'Looking good', improve: 'Needs attention', low: 'Room to improve',
    servicesEyebrow: 'OUR SERVICES', servicesTitle: 'We build. We connect. We improve.',
    services: [
      ['Web development', 'Your business, built for the web.', 'Company websites, web applications and integrations. We plan, design and develop a solution around your users and day-to-day work.'],
      ['Security', 'Understand exposed risks.', 'HTTPS, browser protection headers and configuration. Start with visible signals, then agree on the scope of a deeper review.'],
      ['SEO & GEO', 'Make your business easier to find.', 'Technical SEO, useful content and structured data that help search engines and AI search understand your website.'],
      ['Performance', 'Remove the slowdowns.', 'Find heavy pages and improve loading. Detailed browser performance measurement is a separate review.'],
    ],
    processEyebrow: 'HOW IT WORKS', processTitle: 'From your idea to launch.',
    steps: [['Discover', 'Understand your business, users and goals.'], ['Plan & design', 'Agree on the scope, structure and visual direction.'], ['Build & test', 'Develop the site and test the real user journeys.'], ['Launch & improve', 'Go live, support the site and plan its next steps.']],
    ctaTitle: 'Have a project in mind?', ctaText: 'A new website, a web application or a better version of what you already have.', cta: 'Discuss your project',
    faqTitle: 'Good questions. Clear answers.',
    faq: [
      ['Can you build a new website from scratch?', 'Yes. We can help with the structure, design, development and launch of a new website or web application. Tell us about your business and the tasks it needs to support.'],
      ['Can you improve or maintain our existing website?', 'Yes. We can discuss a redesign, new features, integrations, performance, SEO or security improvements. A preliminary check is one possible starting point, not a requirement.'],
      ['What does the free check cover?', 'The initial HTML of your page, HTTPS, selected response headers, metadata, robots.txt and /sitemap.xml. It does not run scripts, crawl your whole website or attempt to exploit vulnerabilities.'],
      ['Does AI readiness mean my business will appear in ChatGPT?', 'No. This score describes technical signals such as readable HTML, JSON-LD and crawler permissions. It does not measure mentions in AI answers or guarantee visibility. Blocking a crawler can also be an intentional choice.'],
      ['How are the scores calculated?', 'Each observed check has a published weight. The score is the passed weight divided by the total observed weight, multiplied by 100. Unavailable checks are excluded. Expand the report to see every check and its weight.'],
      ['Can CyberAlps help with the changes?', 'Yes. Share your priorities through the contact form. We can discuss the findings, agree on the work and review the result after changes.'],
    ],
    categories: { security: 'Security', seo: 'SEO', ai: 'AI readiness' },
    stages: { queued: 'Waiting for the next available slot…', page: 'Reading the public page…', checks: 'Checking technical signals…', discovery: 'Checking discovery files…', done: 'Check complete' },
    checking: 'Checking website…', retry: 'Try again', evidence: 'Observed evidence', action: 'Suggested next step', weight: 'Weight',
    limitation: 'Technical signals only. This is not a penetration test, a ranking forecast or a measurement of AI mentions.',
    requestTitle: 'Tell us about your project.', requestIntro: 'What would you like to build or improve? You do not need an existing website to get started.',
    optionalWebsite: 'Website (if you already have one)', footerLine: 'Websites. Web applications. Built around you.',
    name: 'Your name', email: 'Email address', website: 'Website', message: 'What can we help with?', send: 'Send request', sending: 'Saving…',
    contactConsent: 'I agree to my details being used to handle this request.',
    success: 'Your request has been saved. Thank you for sharing your project.', close: 'Close',
    privacy: 'Privacy', terms: 'Check terms', contact: 'Contact', back: 'Back to website',
    privacyTitle: 'How this website handles your information',
    privacyText: [
      'A check sends normal HTTP requests to the website you provide. It stores the website address, the findings and a random report identifier for up to 24 hours. Reports are not listed publicly. Anyone with the report identifier may access that report until it expires.',
      'The contact form stores your name, email, website, message, selected language and any linked report identifier for up to 30 days. These details are used to handle your enquiry. This installation stores requests locally; it does not automatically send them to an email or AI provider.',
      'The service uses a temporary, salted hash of your IP address in memory to limit requests. It does not use advertising trackers or third-party analytics. Your language is determined by the page you choose. The hosting provider and reverse proxy may process connection data to deliver the service.',
      'Private recovery copies created during updates can retain deleted records for up to seven additional days. They are used only to recover the service.',
      'Use the contact form to ask about, correct or request deletion of information you submitted. Do not include passwords, access tokens or sensitive personal information in a website address or message.',
    ],
    termsTitle: 'Terms of the preliminary website check',
    termsText: [
      'Only submit websites you own, manage or have permission to assess. Do not use this service to access private networks, third-party confidential information or protected resources.',
      'Findings describe observations at the time of the request. Missing headers or technical signals are prompts for review, not proof of a vulnerability. Successful checks do not establish that a website is secure, compliant or well ranked.',
      'The free check is limited to a page and two discovery files. It does not execute JavaScript, perform an authenticated security assessment, measure Core Web Vitals or measure visibility inside AI-generated answers.',
      'Any implementation work, deeper assessment, price and delivery schedule must be agreed separately. Submitting a contact request does not place a paid order.',
    ],
  },
  de: {
    title: 'CyberAlps | Websites & Webanwendungen entwickeln',
    description: 'Wir gestalten und entwickeln Websites und Webanwendungen für Ihr Unternehmen. Von der neuen Website bis zu Schnittstellen, SEO, KI-Suche und laufender Weiterentwicklung.',
    nav: ['Leistungen', 'Zusammenarbeit', 'Website-Check', 'Kontakt'], check: 'Website prüfen',
    eyebrow: 'WEBSITES & WEBANWENDUNGEN', hero1: 'Ihre neue Website.', hero2: 'Unser Handwerk.',
    intro: 'Wir gestalten und entwickeln Websites und Webanwendungen für Ihr Unternehmen.', intro2: 'Von der ersten Idee bis zum Start — und darüber hinaus.',
    project: 'Projekt besprechen', explore: 'Leistungen entdecken', existing: 'Schon eine Website? Kostenlos prüfen',
    studioTitle: 'Von der Idee zur fertigen Website.', studioLabel: 'WAS WIR ENTWICKELN', studioItems: ['Unternehmenswebsites', 'Webanwendungen', 'Schnittstellen & Automatisierung'],
    studioFoot: 'Design · Entwicklung · Launch · Betreuung',
    auditEyebrow: 'FÜR IHRE BESTEHENDE WEBSITE', auditTitle: 'Ein hilfreicher erster Schritt.', auditIntro: 'Prüfen Sie die technischen Grundlagen Ihrer Website. Entscheiden Sie dann, was Sie verbessern möchten — auf Wunsch mit unserer Unterstützung.',
    placeholder: 'Website-Adresse eingeben', run: 'Kostenlos prüfen', consent: 'Die Website gehört mir oder ich darf sie prüfen lassen.',
    scope: 'SEO & GEO · Sicherheit · Technische Grundlagen', exampleLink: 'Beispielbericht ansehen',
    example: 'Beispielbericht', demo: 'DEMO', live: 'Ihr Website-Check', next: 'Empfohlene nächste Schritte',
    turn: 'Aus Erkenntnissen werden Verbesserungen', plan: 'Massnahmen ansehen', reportTitle: 'Ihre nächsten Schritte. Verständlich erklärt.',
    reportIntro: 'Eine Vorprüfung einer Seite und ihrer Auffindbarkeitsdateien. Öffnen Sie einen Punkt, um den Befund und eine mögliche Massnahme zu sehen.',
    checked: 'Geprüft', issues: 'Zu prüfen', unknown: 'Nicht geprüft', good: 'Gute Grundlage', improve: 'Handlungsbedarf', low: 'Verbesserungspotenzial',
    servicesEyebrow: 'UNSERE LEISTUNGEN', servicesTitle: 'Entwickeln. Verbinden. Verbessern.',
    services: [
      ['Webentwicklung', 'Ihr Unternehmen im Web.', 'Unternehmenswebsites, Webanwendungen und Schnittstellen. Wir planen, gestalten und entwickeln Lösungen für Ihre Nutzer und Ihren Arbeitsalltag.'],
      ['Sicherheit', 'Sichtbare Risiken verstehen.', 'HTTPS, Sicherheits-Header und Konfiguration. Wir beginnen mit sichtbaren Merkmalen und vereinbaren bei Bedarf eine vertiefte Prüfung.'],
      ['SEO & GEO', 'Leichter gefunden werden.', 'Technisches SEO, hilfreiche Inhalte und strukturierte Daten, damit Suchmaschinen und KI-Suche Ihre Website besser verstehen.'],
      ['Performance', 'Bremsen gezielt lösen.', 'Schwere Seiten erkennen und die Ladezeit verbessern. Eine detaillierte Messung im Browser erfolgt in einer separaten Prüfung.'],
    ],
    processEyebrow: 'SO FUNKTIONIERT’S', processTitle: 'Von Ihrer Idee bis zum Start.',
    steps: [['Verstehen', 'Ihr Unternehmen, Ihre Nutzer und Ziele kennenlernen.'], ['Planen & gestalten', 'Umfang, Struktur und Gestaltung gemeinsam abstimmen.'], ['Entwickeln & testen', 'Die Website umsetzen und echte Abläufe prüfen.'], ['Starten & betreuen', 'Veröffentlichen, betreuen und gezielt weiterentwickeln.']],
    ctaTitle: 'Eine Idee für Ihr nächstes Projekt?', ctaText: 'Eine neue Website, eine Webanwendung oder die Weiterentwicklung Ihrer bestehenden Lösung.', cta: 'Projekt besprechen',
    faqTitle: 'Gute Fragen. Klare Antworten.',
    faq: [
      ['Entwickeln Sie auch komplett neue Websites?', 'Ja. Wir unterstützen Sie bei Struktur, Gestaltung, Entwicklung und Veröffentlichung einer neuen Website oder Webanwendung. Erzählen Sie uns von Ihrem Unternehmen und den Aufgaben, die Ihre Lösung erfüllen soll.'],
      ['Können Sie unsere bestehende Website weiterentwickeln?', 'Ja. Wir besprechen Neugestaltung, neue Funktionen, Schnittstellen, Performance, SEO oder Sicherheit. Ein erster Website-Check kann dabei helfen, ist aber keine Voraussetzung.'],
      ['Was umfasst der kostenlose Check?', 'Den ursprünglichen HTML-Inhalt Ihrer Seite, HTTPS, ausgewählte Antwort-Header, Metadaten, robots.txt und /sitemap.xml. Es werden keine Skripte ausgeführt, keine vollständigen Websites durchsucht und keine Schwachstellen ausgenutzt.'],
      ['Bedeutet KI-Bereitschaft, dass mein Unternehmen in ChatGPT erscheint?', 'Nein. Der Wert beschreibt technische Merkmale wie lesbares HTML, JSON-LD und Crawler-Regeln. Er misst keine Erwähnungen in KI-Antworten und garantiert keine Sichtbarkeit. Das Sperren eines Crawlers kann eine bewusste Entscheidung sein.'],
      ['Wie werden die Bewertungen berechnet?', 'Jede beobachtete Prüfung hat ein Gewicht. Die erreichte Gewichtung wird durch die gesamte geprüfte Gewichtung geteilt und mit 100 multipliziert. Nicht verfügbare Prüfungen zählen nicht mit. Der Bericht zeigt jeden Punkt und sein Gewicht.'],
      ['Hilft CyberAlps bei der Umsetzung?', 'Ja. Teilen Sie Ihre Ziele über das Kontaktformular mit. Wir besprechen die Ergebnisse, vereinbaren die Arbeiten und prüfen anschliessend die Wirkung.'],
    ],
    categories: { security: 'Sicherheit', seo: 'SEO', ai: 'KI-Bereitschaft' },
    stages: { queued: 'Warten auf einen freien Platz…', page: 'Öffentliche Seite wird gelesen…', checks: 'Technische Merkmale werden geprüft…', discovery: 'Auffindbarkeitsdateien werden geprüft…', done: 'Prüfung abgeschlossen' },
    checking: 'Website wird geprüft…', retry: 'Erneut versuchen', evidence: 'Beobachteter Befund', action: 'Möglicher nächster Schritt', weight: 'Gewicht',
    limitation: 'Technische Hinweise. Kein Penetrationstest, keine Ranking-Prognose und keine Messung von KI-Erwähnungen.',
    requestTitle: 'Erzählen Sie uns von Ihrem Projekt.', requestIntro: 'Was möchten Sie entwickeln oder verbessern? Sie benötigen dafür noch keine bestehende Website.',
    optionalWebsite: 'Website (falls bereits vorhanden)', footerLine: 'Websites. Webanwendungen. Für Ihr Unternehmen.',
    name: 'Ihr Name', email: 'E-Mail-Adresse', website: 'Website', message: 'Wobei können wir helfen?', send: 'Anfrage senden', sending: 'Wird gespeichert…',
    contactConsent: 'Meine Angaben dürfen zur Bearbeitung dieser Anfrage verwendet werden.',
    success: 'Ihre Anfrage wurde gespeichert. Vielen Dank für Ihr Interesse.', close: 'Schliessen',
    privacy: 'Datenschutz', terms: 'Hinweise zum Check', contact: 'Kontakt', back: 'Zurück zur Website',
    privacyTitle: 'So verarbeitet diese Website Ihre Angaben',
    privacyText: [
      'Der Check ruft die angegebene Website mit normalen HTTP-Anfragen ab. Die Website-Adresse, Ergebnisse und eine zufällige Berichtskennung werden bis zu 24 Stunden gespeichert. Berichte werden nicht öffentlich aufgelistet. Wer die Berichtskennung kennt, kann den Bericht bis zum Ablauf abrufen.',
      'Das Kontaktformular speichert Name, E-Mail-Adresse, Website, Nachricht, gewählte Sprache und gegebenenfalls eine verknüpfte Berichtskennung für bis zu 30 Tage. Die Angaben dienen der Bearbeitung Ihrer Anfrage. Anfragen werden in dieser Installation lokal gespeichert und nicht automatisch an E-Mail- oder KI-Anbieter gesendet.',
      'Zur Begrenzung von Anfragen verwendet der Dienst vorübergehend einen gesalzenen Hash Ihrer IP-Adresse im Arbeitsspeicher. Es gibt keine Werbetracker oder Analysewerkzeuge von Drittanbietern. Die Sprache ergibt sich aus der gewählten Seite. Hosting und Reverse Proxy können Verbindungsdaten zur Bereitstellung des Dienstes verarbeiten.',
      'Private Sicherungskopien bei Aktualisierungen können gelöschte Angaben bis zu sieben weitere Tage enthalten. Sie dienen ausschliesslich der Wiederherstellung des Dienstes.',
      'Über das Kontaktformular können Sie Fragen zu Ihren Angaben stellen sowie Berichtigung oder Löschung anfragen. Geben Sie keine Passwörter, Zugriffsschlüssel oder sensiblen persönlichen Informationen in Website-Adressen oder Nachrichten ein.',
    ],
    termsTitle: 'Hinweise zur vorläufigen Website-Prüfung',
    termsText: [
      'Prüfen Sie nur Websites, die Ihnen gehören, die Sie verwalten oder für deren Prüfung Sie eine Erlaubnis haben. Der Dienst darf nicht zum Zugriff auf private Netzwerke, vertrauliche fremde Informationen oder geschützte Ressourcen genutzt werden.',
      'Ergebnisse beschreiben Beobachtungen zum Zeitpunkt der Anfrage. Fehlende Header oder technische Merkmale sind Hinweise zur Überprüfung, kein Nachweis einer Schwachstelle. Bestandene Prüfungen belegen weder Sicherheit noch Rechtskonformität oder gute Platzierungen.',
      'Der kostenlose Check umfasst eine Seite und zwei Auffindbarkeitsdateien. Er führt kein JavaScript aus, prüft keine angemeldeten Bereiche und misst weder Core Web Vitals noch Sichtbarkeit in KI-generierten Antworten.',
      'Umsetzungsarbeiten, vertiefte Prüfungen, Preise und Termine werden separat vereinbart. Eine Kontaktanfrage ist kein kostenpflichtiger Auftrag.',
    ],
  },
};

export const checks = {
  https: ['HTTPS connection', 'HTTPS-Verbindung', 'Use HTTPS with a valid certificate and redirect HTTP traffic.', 'HTTPS mit gültigem Zertifikat verwenden und HTTP umleiten.'],
  hsts: ['HTTPS enforcement header', 'Header für HTTPS-Erzwingung', 'Review an appropriate Strict-Transport-Security policy after validating HTTPS coverage.', 'Eine geeignete Strict-Transport-Security-Richtlinie nach Prüfung der HTTPS-Abdeckung erwägen.'],
  csp: ['Content Security Policy', 'Content Security Policy', 'Review a CSP tailored to the scripts and resources your site needs. Presence alone does not validate the policy.', 'Eine zu den Ressourcen passende CSP prüfen. Das Vorhandensein bestätigt nicht die Qualität der Richtlinie.'],
  nosniff: ['Content type protection', 'Schutz des Inhaltstyps', 'Review X-Content-Type-Options: nosniff and correct MIME types.', 'X-Content-Type-Options: nosniff und korrekte MIME-Typen prüfen.'],
  framing: ['Embedding protection', 'Schutz vor Einbettung', 'Decide which sites may embed your pages and configure frame-ancestors accordingly.', 'Festlegen, welche Websites Ihre Seiten einbetten dürfen, und frame-ancestors entsprechend konfigurieren.'],
  mixed: ['HTTP resource references', 'HTTP-Ressourcen', 'Review HTTP resource references on HTTPS pages; update resources where appropriate.', 'HTTP-Ressourcen auf HTTPS-Seiten prüfen und gegebenenfalls umstellen.'],
  title: ['Page title', 'Seitentitel', 'Add a clear, unique title describing the page.', 'Einen klaren, eindeutigen und passenden Seitentitel ergänzen.'],
  description: ['Meta description', 'Meta-Beschreibung', 'Describe the page accurately and give searchers a useful reason to visit.', 'Die Seite treffend beschreiben und Suchenden einen hilfreichen Besuchsgrund geben.'],
  h1: ['Main heading', 'Hauptüberschrift', 'Review the main page heading and the heading hierarchy.', 'Hauptüberschrift und Überschriftenhierarchie prüfen.'],
  canonical: ['Canonical URL', 'Kanonische URL', 'Identify the preferred URL and review canonical links.', 'Die bevorzugte URL bestimmen und Canonical-Verweise prüfen.'],
  indexable: ['Indexing directives', 'Indexierungsregeln', 'Check whether noindex is intentional before changing it.', 'Vor einer Änderung prüfen, ob noindex beabsichtigt ist.'],
  viewport: ['Mobile viewport', 'Mobiler Viewport', 'Configure a responsive viewport and verify the page on a phone.', 'Einen responsiven Viewport konfigurieren und die Seite auf einem Telefon prüfen.'],
  alt: ['Image alt attributes', 'Alt-Attribute für Bilder', 'Add meaningful alternatives to informative images; decorative images may use an empty alt.', 'Informativen Bildern sinnvolle Alternativtexte geben; dekorative Bilder dürfen ein leeres alt haben.'],
  language: ['Page language', 'Seitensprache', 'Declare the page language on the HTML element.', 'Die Seitensprache am HTML-Element angeben.'],
  structured: ['Structured data', 'Strukturierte Daten', 'Add relevant JSON-LD matching visible content and validate it against the appropriate schema.', 'Passendes JSON-LD für sichtbare Inhalte ergänzen und gegen das zutreffende Schema prüfen.'],
  readable: ['Readable initial HTML', 'Lesbares ursprüngliches HTML', 'Make essential business information available as HTML without requiring JavaScript.', 'Wichtige Unternehmensinformationen als HTML ohne notwendige JavaScript-Ausführung bereitstellen.'],
  robots: ['robots.txt', 'robots.txt', 'Review crawler rules. A missing robots.txt is not itself a security issue.', 'Crawler-Regeln prüfen. Eine fehlende robots.txt ist für sich kein Sicherheitsproblem.'],
  googlebot: ['Googlebot permission', 'Googlebot-Regeln', 'Review crawler permissions for this page. Robots rules do not guarantee indexing.', 'Crawler-Freigaben für diese Seite prüfen. Robots-Regeln garantieren keine Indexierung.'],
  'oai-searchbot': ['OAI-SearchBot permission', 'OAI-SearchBot-Regeln', 'Review whether search crawling is appropriate for this page; permissions do not guarantee AI mentions.', 'Prüfen, ob Such-Crawling für diese Seite gewünscht ist; Freigaben garantieren keine KI-Erwähnungen.'],
  perplexitybot: ['PerplexityBot permission', 'PerplexityBot-Regeln', 'Review whether this crawler should be allowed. An intentional block may be appropriate.', 'Prüfen, ob dieser Crawler erlaubt sein soll. Eine bewusste Sperre kann sinnvoll sein.'],
  sitemap: ['XML sitemap', 'XML-Sitemap', 'Review /sitemap.xml. This initial check does not discover alternative sitemap locations.', '/sitemap.xml prüfen. Diese Vorprüfung sucht nicht nach alternativen Sitemap-Adressen.'],
};
